version: "3.9"

services:

  postgres:
    image: postgres:14.7-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $POSTGRES_USER
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: daniil77089/todolist:latest
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    command: python manage.py runserver 0.0.0.0:8000

  migrations:
    image: daniil77089/todolist:latest
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
    command: python manage.py migrate

  front:
    image: sermalenk/skypro-front:lesson-34
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  postgres_data:
