version: "3.9"

services:

  postgres:
    image: postgres:14.7-alpine
    restart: always
    environment:
      POSTGRES_DB: $POSTGRES_NAME
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U $POSTGRES_USER -d $POSTGRES_NAME
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: daniil77089/todolist:latest
    links:
      - "postgres:database"
    environment:
      POSTGRES_DB: $POSTGRES_NAME
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 80:80
    depends_on:
      postgres:
        condition: service_healthy
    command: python manage.py migrate && python manage.py runserver

  front:
    image: sermalenk/skypro-front:lesson-34
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - api
